# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ECML

email: g.de.ath@exeter.ac.uk
# >-  ::: this means to ignore newlines until "baseurl:"

description: >- 
   Evolutionary Computation and Machine Learning reading group

# the subpath of your site, e.g. /blog
baseurl: "" 

# the base hostname & protocol for your site, e.g. http://example.com
url: ""
#twitter_username: jekyllrb
github_username:  exeter-ecml

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

plugins:
#  - jekyll-feed
#  - jekyll-paginate
  - jekyll-remote-theme
  - github-pages

# posts per page
#paginate: 5
#paginate_path: '/posts/page:num'
#sort_field: 'paper_no'

sidebar_home_link: true

# collections - so we can iterate over pages
collections:
    papers:
        output: true
        permalink: /:collection/:name
    meetings:
        output: true
        permalink: /:collection/:name
